require_relative 'lee/board'
require_relative 'lee/adjacent'
require_relative 'lee/cost'
require_relative 'lee/matrix'
require_relative 'lee/solver'
require_relative 'lee/tsolver'
require_relative 'lee/validate'
